version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.gradle.publish:plugin-publish-plugin
    versions:
    - 0.12.0
    - 0.13.0
    - 0.14.0
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
