= Arquillian Spacelift Gradle Plugin image:https://travis-ci.org/arquillian/arquillian-spacelift-gradle-plugin.svg["Build Status", link="https://travis-ci.org/arquillian/arquillian-spacelift-gradle-plugin"]

This Gradle plugin is able to prepare test environment and execute tests.
Plugin is using Arquillian Spacelift project to execute external commands. Compatible with Gradle 2.

In order to enable the plugin, define:

[source,groovy]
----
apply plugin: 'spacelift'

// build dependencies
buildscript {
    repositories {
        mavenCentral()
        // you need this only if you plan to use staged version of this plugin
        maven {
            name 'jboss-staging-repository-group'
            url 'https://repository.jboss.org/nexus/content/groups/staging'
        }
        // you need this only if you plan to use version in your local Maven repository
        mavenLocal()
    }
    dependencies {
        classpath 'org.arquillian.spacelift.gradle:arquillian-spacelift-gradle:1.0.0-alpha-3'
    }
}

// these elements are needed only if you are willing to use _testreport_ task
repositories {
    mavenCentral()
}

configurations {
    junitreport
}

dependencies {
    junitreport 'org.apache.ant:ant-junit:1.9.4'
}
----

== Gradle Tasks

This plugin provides following tasks:

assemble::
    Installs all installations defined by profile
check/test::
    Executes tests defined in profile. Depends on +assemble+. Both +check+ and +test+ are the same.
testreport::
    Gathers all test results in JUnit format from workspace and creates a combined report. Requires additional configuration
    in _build.gradle_ file
show-configuration::
    Shows global configuration and available profiles

=== Manual profile definitions

In cases you want to execute only a subset of installations or tests, you can combine activated profile with manual
override of installations and or tests.

For instance, following call installs all installations from *default* profile but executes only *myTestName* test.

[code,bash]
----
gradle -Pprofile=default -Ptests=myTestName test
----

Whereas this call completely ignores profile and installs *myTestNameRequirement* and then executes *myTestName*:

[code,bash]
----
gradle -Pinstallations=myTestNameRequirement -Ptests=myTestName test
----

NOTE: If you want to skip tests or installations altogether, use following syntax +gradle -Pinstallations= test+

== DSL

Plugin uses following DSL structure:

[code,groovy]
----
spacelift {

    workspace value
    installationsDir value
    localRepository value
    killServers value
    keystoreFile value
    truststoreFile value
    enableStaging value
    enableSnapshots value

    tools {
        tool1 { }
    }

    profiles {
        profile1 { }
        profile2(inherits:'profile1') { }
    }

    installations {
        installation1 { }
    }

    tests {
        test1 { }
    }

    
}
----

globalSetupProperties::
    There are a few properties with sane default. You can modify them to alter execution flow.
+
* +workspace+ - a directory where you work, by default this directory 
* +installationsDir+ - a directory where installation files are cached
* +localRepository+ - Maven local repository path
* +killServers+ - {true|false} whether to kill Java processes first
* +keystoreFile+ - path to JKS keystore file
* +truststoreFile+ - path to JKS truststore file
* +enableStaging+ - enable JBoss Staging repository
* +enableSnapshots+ - enable JBoss Snapshots repository


value::
    Value definition in accepted in following format. If it is defined in _block_, is is always lazy evaluated.
+
* _plain_ - such as +false+, +"mydir"+, +'mydir'+ or +"${project.rootDir}/mydir"+.
* _block_ - such as +{ false }+ or +{ /* a lot of code */ }+. Block does has access to properties of defining installation, profile, test or tool, whatever is relevant. It can also reference current project by using +project+ property
* _map_ - a map with keys denoting operating system and value either in _plain_ or _block_ form, for instance +[linux:"foo", windows: {"foo"}]+. Following OS values are supported:
** +linux+
** +windows+
** +mac+
** +solaris+
+
 
NOTE: If you are using a _map_, you need to use parenthesis around parameters

tools::
    Tools allow you to define external commands that should be available on local system. Tools can be inherited from previously defined tools.
+
[source,groovy]
----
toolName {
    command value
}
----
+
command::
    Command defines what will be executed. In case you provide _string_ or _list of strings_, it will be transformed to 
    Spacelift +CommandTool+. In case you are using _block_, you are supposed to return +CommandTool+. In case of
    map, you can use *windows*, *linux*, *mac* and *solaris* keys that will match the platform. The block will register a +CommandTool+ 
    you can retrieve by +GradleSpacelift.tools('toolName')+ later on.
    Following tools are always expected to be present: _ant_ and _mvn_

profiles::
    Profiles consist of installations to be installed and tests to be executed. You can use -P__profileName__ to trigger
    specific profile, otherwise default profile is triggered. _default_ profile is expected to be present. Note, you need
    define profileName quoted in case of _default_. Profiles can be inherited from previous created profiles.
+
[source,groovy]
----
profileName {
    enabledInstallations 'installation1', 'installation2'
    tests 'test1', 'test3', 'test27'
    excludedTests 'test3'
}
----
+

You can exclude tests from execution by _excludedTests_ on profile where you specify which tests you do not want to execute. By triggering the above profile, only _test1_ and _test27_ will be executed.

NOTE: You can also use +*+ to enable all defined installations and or tests for profile. And you can also use _value_ notion and construct a list of strings to match installation names.


installations::
    Installations provides a way how to bring additional tools to you test environment. Installation is automatically downloaded
    or fetched from local cache and extracted, based on current OS. Installations can be inherited from previously defined installations.
+
[source,groovy]
----
installationName {
    product value
    version value
    fileName value
    remoteUrl value
    home value
    autoExtract value
    forceReinstall value 
    preconditions value 
    }
    extractMapper { /* Any UncompressTool call(s) */ }
    tools {
        tool1 {
            command value
        }
    }
    postActions {
    }
}
otherInstallation(inherits:'installationName') {
    // reuses all values from 'installationName', redefines home
    home newValue
}
----
+
Following properties are used::

* product - name of product, used for storing installation in _installationsDir_
* version - version of product, used for storing installation in _installationsDir_
* fileName - name of file as downloaded in _workspace_. Can be map, same keys as for _tool_
* remoteUrl - URL where to download from. Can be map, same keys as for _tool_
* home - name of dir in _workspace_ where installation is extracted. Can be map, same keys as for _tool_
* autoExtract - by default +true+, consider installation an archive and extract it to _workspace_ directory
* forceReinstall - by default +false+, ignores installation download and extract if already available in _installationDir_ or extracted in _workspace_
* extractMapper - optional calls on https://github.com/arquillian/arquillian-spacelift/blob/master/spacelift-impl/src/main/java/org/arquillian/spacelift/tool/basic/UncompressTool.java[UncompressTool] performed prior extraction happens. For instance, this removes first directory from extracted path and extracts archive to directory defined by +home+
+
[source]
----
extractMapper {
    toDir(home)
    cutdirs()
}
----
+
* tools - allows to define tool(s) that will be available after installation is done, same syntax as _tools_ block_
* postActions - defines actions to be performed after installation is extracted
* preconditions - this closure is optional and when specified, it has to return boolean value. If it returns false, installation is skipped, if true, installation is executed.

tests::
    Tests define a block of commands to be executed in *test* Gradle task. If you provide +dataProvider+ block, test
    execution (including before and after test phases) will iterate over data provided. Tests can inherit from previously defined tests

[source,groovy]
----
testName {
    dataProvider {
        // return an array here, allows to parametrize tests
    }
    beforeSuite { 
        // executed once prior all tests
    }
    beforeTest { value ->
        // executed prior test
    }
    execute { value ->
        // your commands here
    }
    afterTest { value ->
        // executed after test
    }
    afterSuite {
        // executed once prior all tests
    }
}
----

== Execution parameters

It is possible to modify what tests will be run and what installations will be installed. Apart from profile option, you can use:

[source,bash]
----
-Pinstallations=comma,separated,values
-Ptests=comma,separated,values
----

This will ignore installations and tests defined by profile and instead will install +comma+, +separated+ and +value+. If _test_ task is executed,
it will perform test execution for tests +comma+, +separated+ and +value+.

If you need to reference profile, installations or tests from Gradle script, these are exposed as:

* +project.selectedProfile+
* +project.selectedInstallations+
* +project.selectedTests+

All represented by appropriate object.


== Default values

Groovy allows user to specify additional project properties using +ext+ block:

[source,groovy]
----
ext {
    property = value
}
----

You can use this block to store global objects needed during execution.
The plugin additionally allows following goodies for property definitions:

Default values::
    If a property starts with +default+, it is used if user won't override it from command line. Example: +defaultAndroidVersion=19+ will 
    become available as +androidVersion+ property in the project.
Overriding default values::
    User can override any default value by using +-PpropertyName=value+ from command line. Example: +-PandroidVersion=17,18+ will override
    +defaultAndroidVersion+ value with +[18,19]+.
Parsing of user supplied values::
    User defined properties on command line are automatically split by +,+ character and converted into array.

== Spacelift Tools and Task

You can benefit from following tools and tasks, either from Spacelift itself or provided by this plugin:

* DownloadTool - downloads a file
* UnzipTool - extracts a zip file
* CommandTool - executes external command
* AntExecutor - executes Ant command. Requires _ant_ tool
* MavenExecutor - executes Maven command. Requires _mvn_ tool
* JavaExecutor - executes Java command. Requires _java_ tool
* XmlFileLoader - loads xml from file into +Node+
* XmlTextLoader - loads xml from text into +Node+
* XmlUpdater - stores +Node+ into file
* ArquillianXmlUpdater - updates container and/or extension properties in _arquillian.xml_ files
* PomXmlUpdater - updates properties in _pom.xml_ files
* SettingsXmlUpdater - updates _settings.xml_ with additional repositories, sets +localRepository+
* KillJavas - kills running Java processes (Selenium, JBoss AS/WildFly containers) and processes occupying ports
* StandaloneXmlUpdater - allows to add keystore/truststore configuration to _standalone.xml_
* DomainXmlUpdater - allows to add keystore/truststore configuration to _domain.xml_
* AndroidSdkUpdater - allows to fetch binaries for specific Android SDK target - you need to agree with Android SDK license first. Requires _android_ tool.
* AndroidSdkOptForStats - allows to opt out for stats - you need to agree with Android SDK license first
* AndroidEmulatorStarter - starts Android emulator
* AndroidEmulatorStopper - stops Android emulator
* AVDCreator - creates Android Virtual Devices
* CordovaExecutor - executes Cordova commands
* RHELVersion - determines version of RHEL system

== Release new version

Follow this process to release new version:

1. Update version to release version in _build.gradle_
2. Execute +gradle publish -Dmaven.settings=/path/to/settings.xml+. Note that your settings.xml need to contain JBoss Nexus repository configuration, according to
    *Deploy to the JBoss Repository* section at https://developer.jboss.org/wiki/MavenGettingStarted-Developers
3. Tag current commit via +git tag+
4. Bump version to next development version

== Releasing SNAPSHOT version to local Maven Repository

In order to build and publish SNAPSHOT plugin, use +gradle build publishToMavenLocal+.
